---
title: "Survival Analysis Project"
author: "Kotaro Ito"
date: "2025-04-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Setup/Cleaning

```{r}
library(survival)
library(dplyr)
colSums(is.na(colon))
e1 <- colon[colon$etype == 1,]
e2 <- colon[colon$etype == 2,]
lapply(colon, class)
colon_clean <- colon %>%
  mutate(differ = case_when(
    differ == 1 ~ "Well Differentiated",
    differ == 2 ~ "Moderately Differentiated",
    differ == 3 ~ "Poorly Differentiated"
  )) %>%
  mutate(differ = as.factor(differ),
         etype = as.factor(etype),
         sex = as.factor(sex),
         obstruct = as.factor(obstruct),
         perfor = as.factor(perfor),
         adhere = as.factor(adhere),
         node4 = as.factor(node4),
         surg = as.factor(surg),
         extent = as.factor(extent)) %>%
  na.omit()
colon_clean

sum(colon_clean$rx == "Lev+5FU")
sum(colon_clean$rx == "Lev")
sum(colon_clean$rx == "Obs")

```

## Log-Log Plots
```{r}
exclude <- c("id", "nodes", "time", "status", "etype", "age")
covariates <- setdiff(names(colon), exclude)
for (cov in covariates) {
  f <- as.formula(paste("Surv(time, status) ~", cov))
  fit <- survfit(f, data = colon)
  plot(fit, fun = "cloglog",
       col = 1:10,
       main = paste("Log-Log Plot by", cov),
       xlab = "log(Time)",
       ylab = "log(-log(Survival))")
  if (is.factor(colon[[cov]])) {
legend("bottomleft", legend = levels(colon[[cov]]),
           col = 1:length(levels(colon[[cov]])), lty = 1)}}

```

## Assumption Check for other Covariates
```{r}
cox_model <- coxph(Surv(time, status) ~ age, data = colon)
test_ph <- cox.zph(cox_model)
test_ph
# age returns p-value of 0.93(does not violate coxph assumption)
```

## Counting Process 
```{r}
library(dplyr)
colon_clean$start <- 0
colon_clean$stop <- colon_clean$time

# splitting dataset by etype
rec <- colon_clean %>% filter(etype == 1)
death <- colon_clean %>% filter(etype == 2)


# adding a start and stop for rec
rec <- rec %>%
  mutate(start = 0,
         stop = time)

# take the id and rec_time of rec dataset and merge into death by id
# change death start time and stop time
death <- death %>%
  left_join(rec %>% select(id, rec_time = time), by = "id") %>%
  mutate(
    start = rec_time,
    stop = time
  )

# merge the rec and death as the new dataset 
# remove rec_time(helper variable)

colon_clean <- bind_rows(rec, death) %>%
  arrange(id) %>%
  select(-rec_time) %>%
  mutate(start = if_else(start == stop, 0, start))

# remove rownames(idk why but it was messy)
rownames(colon_clean) <- NULL


colon_clean

cox_cp <- coxph(Surv(start, stop, status) ~ rx + extent + nodes, data = colon_clean)

summary(cox_cp)
```




